"""Planejamento do quadro Kanban (regenerado do board refinado).

Fonte de verdade das colunas/descrições/prioridades. Editável; o board
vive no arquivo persistido após o primeiro seed.
"""

SEED_CARDS: list[dict] = [
    {
        'title': 'Agente revisor/editor de roteiros (loop de melhoria)',
        'description': 'Loop crítica→reescrita: reescreve o roteiro a partir do feedback do crítico e re-avalia até a nota mínima (máx N iterações), em vez de só rejeitar. Aceite: nota final ≥ limiar e nº de iterações/delta logados. Depende de: agente crítico (feito) + ScriptWriterAgent (feito).',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'conteúdo', 'prioridade:alta'],
    },
    {
        'title': 'Abstração de provedor de LLM (texto)',
        'description': "get_text_generator(config) espelhando agents/media; OllamaClient vira o provider 'ollama'. Aceite: trocar provider por config sem mexer nos agentes; todos os agentes passam pelo factory. Alicerce da Sprint 9.",
        'column': 'done',
        'sprint': 'Sprint 9 · Troca de modelos',
        'labels': ['backend', 'prioridade:alta'],
    },
    {
        'title': 'Persistência em SQLite',
        'description': 'Migrar fila/board dos JSON para SQLite mantendo a interface pública. Aceite: testes verdes; escrita/leitura concorrente sem corrupção; migra o JSON existente. Mitigação atual: escrita atômica (tmp+os.replace).',
        'column': 'backlog',
        'sprint': 'Sprint 7 · Robustez',
        'labels': ['backend', 'prioridade:alta'],
    },
    {
        'title': 'Registry unificado de modelos',
        'description': 'config + GET /api/models por capacidade (texto/imagem/voz/vídeo), providers e modelos; valida seleções. Aceite: /api/models lista tudo com os padrões atuais. Depende de: abstração de LLM (texto).',
        'column': 'done',
        'sprint': 'Sprint 9 · Troca de modelos',
        'labels': ['backend', 'prioridade:média'],
    },
    {
        'title': 'Dashboard de métricas real',
        'description': 'Aba no frontend: KPIs (pendentes/aprovadas/postadas), views/likes por vídeo e insights do analista. Aceite: consome /api/ideas e /api/analyze e atualiza ao vivo. Depende de: coleta automática de métricas (p/ dados reais).',
        'column': 'backlog',
        'sprint': 'Sprint 8 · Métricas & Escala',
        'labels': ['frontend', 'backend', 'prioridade:média'],
    },
    {
        'title': 'Assistente OAuth self-service',
        'description': "UI guiada p/ gerar/renovar refresh tokens sem editar .env. Aceite: conectar uma conta pelo painel e publicar. Depende de: 'OAuth / credenciais' (backend).",
        'column': 'backlog',
        'sprint': 'Sprint 8 · Métricas & Escala',
        'labels': ['backend', 'frontend', 'integração', 'prioridade:média'],
    },
    {
        'title': 'OAuth / credenciais das plataformas',
        'description': 'Backend: troca código→refresh token + armazenamento seguro (fora do git) por plataforma. Aceite: obter/persistir refresh token do YouTube e publisher usar sem editar .env. Base do Assistente OAuth (UI).',
        'column': 'backlog',
        'sprint': 'Sprint 3 · Publicação',
        'labels': ['backend', 'integração', 'prioridade:média'],
    },
    {
        'title': 'Coleta automática de métricas',
        'description': 'Job que puxa métricas via APIs (YouTube Analytics/Meta Insights/TikTok) e grava em Idea.metrics; alimenta o analista. Aceite: métricas de ≥1 plataforma populadas automaticamente. Depende de: OAuth.',
        'column': 'backlog',
        'sprint': 'Sprint 8 · Métricas & Escala',
        'labels': ['backend', 'integração', 'prioridade:média'],
    },
    {
        'title': 'Painel de troca de modelos (UI)',
        'description': 'Aba de config no frontend p/ escolher provider+modelo por capacidade. Aceite: trocar modelo pela UI reflete no backend. Depende de: registry + descoberta de modelos.',
        'column': 'done',
        'sprint': 'Sprint 9 · Troca de modelos',
        'labels': ['frontend', 'prioridade:média'],
    },
    {
        'title': 'Override de modelo por agente',
        'description': 'Modelo por agente sobre o padrão global (ex.: critic_model). Aceite: crítico e ideias podem usar modelos distintos. Depende de: abstração de LLM (texto).',
        'column': 'done',
        'sprint': 'Sprint 9 · Troca de modelos',
        'labels': ['backend', 'prioridade:baixa'],
    },
    {
        'title': 'Descoberta de modelos disponíveis',
        'description': 'Listar modelos do Ollama (/api/tags) e dos provedores p/ popular a UI. Aceite: endpoint retorna modelos instalados/configurados.',
        'column': 'done',
        'sprint': 'Sprint 9 · Troca de modelos',
        'labels': ['backend', 'integração', 'prioridade:baixa'],
    },
    {
        'title': 'Mais plataformas de publicação',
        'description': 'Novos publishers (Facebook Reels, Kwai, X) no mesmo gancho get_publisher. Aceite: ≥1 nova rede publica de fato. Depende de: OAuth/credenciais.',
        'column': 'backlog',
        'sprint': 'Sprint 8 · Métricas & Escala',
        'labels': ['backend', 'integração', 'prioridade:baixa'],
    },
    {
        'title': 'Documentação final e publicação do projeto',
        'description': 'README/HANDOFF revisados, licença, guia de execução e diagrama de arquitetura. Aceite: reproduzível do zero seguindo o README; licença definida; main como default (pelo dono).',
        'column': 'backlog',
        'sprint': 'Sprint 4 · Deploy & Publicação',
        'labels': ['docs', 'prioridade:baixa'],
    },
    {
        'title': 'Publisher via API oficial (1 plataforma)',
        'description': 'YouTube Data API v3 implementado (upload real via google-api-python-client). Em revisão até validar com o token OAuth no .env.',
        'column': 'review',
        'sprint': 'Sprint 3 · Publicação',
        'labels': ['backend', 'integração'],
    },
    {
        'title': 'Publisher Instagram Reels',
        'description': 'publishers/instagram.py (Graph API) — scaffold; falta URL pública do vídeo + chamada final. IG_USER_ID/IG_ACCESS_TOKEN.',
        'column': 'review',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'integração'],
    },
    {
        'title': 'Publisher TikTok',
        'description': 'publishers/tiktok.py (Content Posting API) — scaffold; falta completar o fluxo de upload. TIKTOK_ACCESS_TOKEN.',
        'column': 'review',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'integração'],
    },
    {
        'title': 'Scaffold do projeto (agentes, pipeline, painel)',
        'description': 'Estrutura inicial: agente de estratégia (Ollama), esqueleto do pipeline de vídeo e painel Streamlit.',
        'column': 'done',
        'sprint': 'Sprint 0 · Fundação',
        'labels': ['backend'],
    },
    {
        'title': 'Cliente Ollama compartilhado',
        'description': 'OllamaClient com generate() e extract_json() (tolerante a cercas de código e a topo {}/[]). Remove duplicação entre agentes.',
        'column': 'done',
        'sprint': 'Sprint 0 · Fundação',
        'labels': ['backend'],
    },
    {
        'title': 'Agente roteirista cena-a-cena',
        'description': 'ScriptWriterAgent: trending_topic → list[Scene]/VideoJob pronto para o VideoPipeline.',
        'column': 'done',
        'sprint': 'Sprint 0 · Fundação',
        'labels': ['backend'],
    },
    {
        'title': 'Testes de parsing (JSON + cenas)',
        'description': '14 testes offline de extract_json e build_scenes.',
        'column': 'done',
        'sprint': 'Sprint 0 · Fundação',
        'labels': ['testes'],
    },
    {
        'title': 'Modelo de ideia + fila de revisão',
        'description': 'Idea (com estados) e ReviewQueue persistida em JSON.',
        'column': 'done',
        'sprint': 'Sprint 1 · Esteira de aprovação',
        'labels': ['backend'],
    },
    {
        'title': 'Gerador de ideias a partir de prompt',
        'description': 'IdeaGenerator: brainstorm de conceitos + roteiro por conceito → lista de Idea.',
        'column': 'done',
        'sprint': 'Sprint 1 · Esteira de aprovação',
        'labels': ['backend'],
    },
    {
        'title': 'Engine: modos manual e auto',
        'description': 'generate_and_enqueue + post_approved. Manual = fila Tinder; auto = prompta-e-posta (publisher via API oficial, ainda desconectado).',
        'column': 'done',
        'sprint': 'Sprint 1 · Esteira de aprovação',
        'labels': ['backend'],
    },
    {
        'title': 'API HTTP (FastAPI)',
        'description': 'Endpoints de gerar/listar/aprovar/rejeitar/postar e do board.',
        'column': 'done',
        'sprint': 'Sprint 1 · Esteira de aprovação',
        'labels': ['backend'],
    },
    {
        'title': 'Interface Next.js — aba Ideias (Tinder)',
        'description': 'Prompt + modo (manual/auto), cartões de aprovação (❌/✅), lista de aprovadas prontas para postar.',
        'column': 'done',
        'sprint': 'Sprint 1 · Esteira de aprovação',
        'labels': ['frontend'],
    },
    {
        'title': 'Interface Next.js — aba Kanban',
        'description': 'Quadro de sprints com arrastar-e-soltar entre colunas.',
        'column': 'done',
        'sprint': 'Sprint 1 · Esteira de aprovação',
        'labels': ['frontend'],
    },
    {
        'title': 'Testes da fila de revisão e do gerador',
        'description': 'ReviewQueue, engine, BoardStore e build_idea_concepts — 47 testes no total.',
        'column': 'done',
        'sprint': 'Sprint 1 · Esteira de aprovação',
        'labels': ['testes'],
    },
    {
        'title': 'Gerador de imagem plugável',
        'description': 'Fábrica agents/media: placeholder (FFmpeg) por padrão + stub Stability (STABILITY_API_KEY). Selecionável por config/env.',
        'column': 'done',
        'sprint': 'Sprint 2 · Geração de mídia',
        'labels': ['backend', 'conteúdo'],
    },
    {
        'title': 'Gerador de voz/TTS plugável',
        'description': 'Fábrica agents/media: placeholder (áudio) por padrão + stub ElevenLabs (ELEVENLABS_API_KEY).',
        'column': 'done',
        'sprint': 'Sprint 2 · Geração de mídia',
        'labels': ['backend', 'conteúdo'],
    },
    {
        'title': 'Provedor Gemini (imagem e vídeo)',
        'description': 'image_provider=gemini (Imagen) e video_provider=gemini (Veo, clipe por cena com muxagem de narração/legenda). GEMINI_API_KEY no .env.',
        'column': 'done',
        'sprint': 'Sprint 2 · Geração de mídia',
        'labels': ['backend', 'conteúdo', 'integração'],
    },
    {
        'title': 'Legendas / burn-in no vídeo',
        'description': 'drawtext do FFmpeg queima a narração por cena (config burn_subtitles); escape de fonte cross-platform (Windows/Linux).',
        'column': 'done',
        'sprint': 'Sprint 2 · Geração de mídia',
        'labels': ['backend', 'conteúdo'],
    },
    {
        'title': 'Teste de integração do VideoPipeline',
        'description': 'tests/test_video_pipeline.py cobre render/concat/legendas mockando FFmpeg e os geradores.',
        'column': 'done',
        'sprint': 'Sprint 2 · Geração de mídia',
        'labels': ['testes'],
    },
    {
        'title': 'Ligar geração de vídeo à esteira de ideias',
        'description': 'render.py + POST /api/ideas/{id}/render anexa video_path; frontend tem botão Renderizar e player de preview.',
        'column': 'done',
        'sprint': 'Sprint 2 · Geração de mídia',
        'labels': ['backend', 'frontend'],
    },
    {
        'title': 'Agendamento de postagens',
        'description': 'Scheduler local (APScheduler) publica ideias aprovadas por intervalo; aba Agendamento no frontend + endpoints. Modo simulado sem token.',
        'column': 'done',
        'sprint': 'Sprint 3 · Publicação',
        'labels': ['backend', 'frontend'],
    },
    {
        'title': 'Dockerfile do backend + build do frontend',
        'description': 'API (uvicorn) + build standalone do Next.js + docker-compose com o Ollama containerizado.',
        'column': 'done',
        'sprint': 'Sprint 4 · Deploy & Publicação',
        'labels': ['infra'],
    },
    {
        'title': 'CI no GitHub Actions',
        'description': 'Roda pytest e next build a cada push/PR (.github/workflows/ci.yml).',
        'column': 'done',
        'sprint': 'Sprint 4 · Deploy & Publicação',
        'labels': ['infra', 'testes'],
    },
    {
        'title': 'Deploy do backend e do frontend',
        'description': 'Hospedagem 100% local via docker compose (restart: unless-stopped) — ollama + api + web + Ollama, tudo na máquina do usuário.',
        'column': 'done',
        'sprint': 'Sprint 4 · Deploy & Publicação',
        'labels': ['infra'],
    },
    {
        'title': 'Bot do Telegram — operar a arquitetura completa',
        'description': 'telegram_bot.py: /gerar e /auto <prompt>, /pendentes, /aprovadas — reusa a API. Serviço opt-in no compose (profile bot). No ar e validado (@bot conectado à API).',
        'column': 'done',
        'sprint': 'Sprint 5 · Bot do Telegram',
        'labels': ['backend', 'integração'],
    },
    {
        'title': 'Bot do Telegram — aprovação por botões inline',
        'description': 'Cada ideia vira mensagem com botões ✅/❌ (approve/reject) e 🎬/🚀 (render/post) via callbacks para a API.',
        'column': 'done',
        'sprint': 'Sprint 5 · Bot do Telegram',
        'labels': ['backend', 'integração'],
    },
    {
        'title': 'Agente crítico (quality gate)',
        'description': 'agents/critic.py dá nota 0-10 à ideia; abaixo do limiar (critic_min_score) é auto-rejeitada antes da revisão. Liga por critic_enabled.',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'conteúdo'],
    },
    {
        'title': 'Geração automática de ideias (agendada)',
        'description': 'Scheduler gera ideias sozinho por intervalo a partir de um prompt fixo (autogen_*), mantendo a esteira cheia. Aba Agendamento.',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'frontend'],
    },
    {
        'title': 'Notificações no Telegram',
        'description': 'Bot avisa proativamente quando surgem ideias pendentes (JobQueue + TELEGRAM_NOTIFY_CHAT_ID).',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'integração'],
    },
    {
        'title': 'Agente analista (feedback loop)',
        'description': 'Puxa métricas dos posts (views/engajamento) e realimenta a estratégia de nicho, favorecendo formatos que performam.',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'integração'],
    },
    {
        'title': 'Thumbnails + A/B de títulos',
        'description': 'Gerar capa (provedor de imagem) e 2-3 títulos alternativos; escolher via agente analista/crítico.',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'conteúdo'],
    },
    {
        'title': 'Legendas multi-idioma',
        'description': 'Traduzir a narração (LLM) e renderizar variantes localizadas (PT/EN/ES) para canais diferentes.',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'conteúdo'],
    },
    {
        'title': 'Trilha sonora royalty-free',
        'description': 'Adicionar música de fundo por cena/vídeo (mix com a narração).',
        'column': 'done',
        'sprint': 'Sprint 6 · Automações',
        'labels': ['backend', 'conteúdo'],
    },
    {
        'title': 'Autenticação da API/web',
        'description': 'Token/login para proteger a API e o painel caso saiam do localhost.',
        'column': 'done',
        'sprint': 'Sprint 7 · Robustez',
        'labels': ['backend', 'infra'],
    },
    {
        'title': 'Geração assíncrona (jobs + status)',
        'description': 'Tornar /api/generate um job em background com polling de status, evitando timeouts em lotes grandes.',
        'column': 'done',
        'sprint': 'Sprint 7 · Robustez',
        'labels': ['backend'],
    },
    {
        'title': 'Testes de integração HTTP',
        'description': 'Cobrir os endpoints do server.py ponta a ponta (TestClient).',
        'column': 'done',
        'sprint': 'Sprint 7 · Robustez',
        'labels': ['testes'],
    },
    {
        'title': 'Retry/backoff nas APIs externas',
        'description': 'Reexecução com backoff em Ollama/Gemini/publishers e tratamento de falha de render.',
        'column': 'done',
        'sprint': 'Sprint 7 · Robustez',
        'labels': ['backend'],
    },
]
